name: Run Stitch Intelligence

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:
jobs:
  run-butcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Поставим стабильную свежую версию
      - name: Install deps
        run: pip install -r intelligence/requirements.txt
      - name: Execute
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: python intelligence/butcher.py
